name: gg_gltf
description: gg_gltf a library for parsing and generating gltf 3D graphic files
version: 1.0.0
repository: https://github.com/inlavigo/gg_gltf.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
