name: gg_gltf
description: gg_gltf a library for parsing and generating gltf 3D graphic files
version: 0.0.1
repository: https://github.com/inlavigo/gg_gltf.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  json_annotation: ^4.9.0
  path: ^1.8.0

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  lints: ^3.0.0
  test: ^1.24.0
